namespace JobsAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            ConditionalJobAttributes = new HashSet<ConditionalJobAttribute>();
            JobMessages = new HashSet<JobMessage>();
            Jobs1 = new HashSet<Job>();
            JobSelections = new HashSet<JobSelection>();
        }

        public int JobID { get; set; }

        public Guid TransactionUID { get; set; }

        public int? FileID { get; set; }

        public int? RootJobID { get; set; }

        public int? SourceJobID { get; set; }

        public int? ParentJobID { get; set; }

        public bool Hidden { get; set; }

        public bool Committed { get; set; }

        public DateTime? Moved { get; set; }

        public DateTime? Deleted { get; set; }

        public bool HasFile { get; set; }

        public int? DestinationID { get; set; }

        [StringLength(255)]
        public string DestinationName { get; set; }

        public int? JobStateID { get; set; }

        public int? SubJobStateID { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int? AggregateJobStateID { get; set; }

        public int? CheckpointID { get; set; }

        [StringLength(255)]
        public string CheckpointName { get; set; }

        public int SubJobCount { get; set; }

        public int SubJobRecycledCount { get; set; }

        public int SubJobHeldCount { get; set; }

        public int SubJobCancelledCount { get; set; }

        public int SubJobErroredCount { get; set; }

        public int SubJobCompletedCount { get; set; }

        public int SubJobProcessingCount { get; set; }

        [StringLength(255)]
        public string JobStatusMessage { get; set; }

        public int? JobPriorityID { get; set; }

        public long? JobSize { get; set; }

        [StringLength(255)]
        public string JobTags { get; set; }

        public int? FolderID { get; set; }

        public DateTime Created { get; set; }

        [Required]
        [StringLength(255)]
        public string CreatedBy { get; set; }

        public DateTime? Released { get; set; }

        [StringLength(255)]
        public string ReleasedBy { get; set; }

        [StringLength(255)]
        public string ReleasedBySID { get; set; }

        public int? DeviceID { get; set; }

        [StringLength(255)]
        public string DeviceName { get; set; }

        [StringLength(255)]
        public string DeviceMachine { get; set; }

        public DateTime LastStateUpdate { get; set; }

        public bool Recycled { get; set; }

        public DateTime? RecycledOn { get; set; }

        public bool AutoGenerated { get; set; }

        public DateTime? AutoReleaseTime { get; set; }

        public bool IsTemplate { get; set; }

        [StringLength(255)]
        public string IJobName { get; set; }

        [StringLength(255)]
        public string IExtName { get; set; }

        [StringLength(255)]
        public string JobClassName { get; set; }

        public int? JobCopies { get; set; }

        public int? DestinationPort { get; set; }

        [StringLength(255)]
        public string JobIDSPDE { get; set; }

        public int? CopiesRendered { get; set; }

        public int? PageRangeStart { get; set; }

        public int? PageRangeEnd { get; set; }

        public int? TotalImpressions { get; set; }

        public DateTime? ProcessingStarted { get; set; }

        public DateTime? ProcessingEnded { get; set; }

        [StringLength(255)]
        public string JobDescription { get; set; }

        [StringLength(255)]
        public string OJobName { get; set; }

        [StringLength(255)]
        public string HostName { get; set; }

        [StringLength(255)]
        public string LocalHostName { get; set; }

        [StringLength(255)]
        public string SPDEDestinationName { get; set; }

        [StringLength(255)]
        public string JobAccountName { get; set; }

        [StringLength(255)]
        public string SPDEUserName { get; set; }

        [StringLength(255)]
        public string HostType { get; set; }

        [StringLength(255)]
        public string SPDEDestinationType { get; set; }

        [StringLength(255)]
        public string SPDEDestinationAddress { get; set; }

        [StringLength(255)]
        public string SPDEDestinationQueue { get; set; }

        [StringLength(255)]
        public string JobType { get; set; }

        [StringLength(255)]
        public string FormName { get; set; }

        [StringLength(255)]
        public string XeroxJdlName { get; set; }

        [StringLength(255)]
        public string XeroxJdeName { get; set; }

        [StringLength(255)]
        public string XchangeString { get; set; }

        [StringLength(255)]
        public string XchangeOpMsgString { get; set; }

        public int? PageCount { get; set; }

        [StringLength(255)]
        public string FcbName { get; set; }

        [StringLength(255)]
        public string InkColor { get; set; }

        [StringLength(255)]
        public string AfpFormDef { get; set; }

        [StringLength(255)]
        public string AfpPageDef { get; set; }

        [StringLength(255)]
        public string SPDELpdQueueName { get; set; }

        public int? CompletedImpressions { get; set; }

        public int? TotalSheets { get; set; }

        public int? CompletedSheets { get; set; }

        [StringLength(255)]
        public string Category1 { get; set; }

        [StringLength(255)]
        public string Category2 { get; set; }

        [StringLength(255)]
        public string Category3 { get; set; }

        [StringLength(255)]
        public string Category4 { get; set; }

        public int? AccountID { get; set; }

        [StringLength(255)]
        public string ConfigurationFile { get; set; }

        [StringLength(255)]
        public string FontMapFile { get; set; }

        [StringLength(255)]
        public string WorkingFolder { get; set; }

        [StringLength(255)]
        public string ResourceFolder { get; set; }

        [StringLength(255)]
        public string UCSB { get; set; }

        [StringLength(255)]
        public string JDT { get; set; }

        public DateTime? DueDate { get; set; }

        [StringLength(255)]
        public string DeviceJobIdentifier { get; set; }

        [StringLength(255)]
        public string ApplicationName { get; set; }

        [StringLength(255)]
        public string ApplicationHost { get; set; }

        [StringLength(255)]
        public string DisplayJobName { get; set; }

        public int? ReconcileJobID { get; set; }

        public int? SiteID { get; set; }

        public int? CompletedColorImpressions { get; set; }

        public int? TotalColorImpressions { get; set; }

        [StringLength(255)]
        public string UnresolvedParentJobIDSPDE { get; set; }

        public int? WorkflowTransactionID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConditionalJobAttribute> ConditionalJobAttributes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobMessage> JobMessages { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs1 { get; set; }

        public virtual Job Job1 { get; set; }

        public virtual Site Site { get; set; }

        public virtual WorkflowTransaction WorkflowTransaction { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSelection> JobSelections { get; set; }
    }
}
